cs3750LMS/cs3750LMS/Models/entites/Submission.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace cs3750LMS.Models.entites
{
    public class Submission
    {
        [Key]
        public int SubmissionID { get; set; }

        public int AssignmentID { get; set; }

        public int StudentID { get; set; }

        public DateTime SubmissionDate { get; set; }

        public int SubmissionType { get; set; }
   
        public int Grade { get; set; }
        public string Contents { get; set; }
    }
}

cs3750LMS/cs3750LMS/Models/general/Instructor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cs3750LMS.Models.general
{
    public class Instructor
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

cs3750LMS/cs3750LMS/Controllers/InstructorController.cs
using cs3750LMS.DataAccess;
using cs3750LMS.Models;
using cs3750LMS.Models.entites;
using cs3750LMS.Models.general;
using cs3750LMS.Models.Repository;
using cs3750LMS.Models.validation;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;


namespace cs3750LMS.Controllers
{
    public class InstructorController : Controller
    {
        private readonly cs3750Context _context;
        private IHostingEnvironment Environment;
        private readonly INotificationRepository _notification;
        private PublicController publicController;
        public InstructorController(cs3750Context context, IHostingEnvironment _environment, INotificationRepository _notification)
        {
            _context = context;
            Environment = _environment;
            this._notification = _notification;
            publicController = new PublicController(_context, _environment, _notification);
        }
        //(begin)Deletions of a Course Logics(begin)----------------------------
        [HttpGet]
        public IActionResult DeleteCourse(int id)
        {
            //set courses object for next pass
            string serialCourse = HttpContext.Session.GetString("userCourses");
            Courses userCourses = serialCourse == null ? null : JsonSerializer.Deserialize<Courses>(serialCourse);
            //make sure course exists, if not send to index
            if (userCourses.CourseList.Count(x=>x.CourseID == id)<1)
            {
                string serialUser = HttpContext.Session.GetString("userInfo");
                UserSession session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);

                string serialCourseb = HttpContext.Session.GetString("userCourses");
                Courses userCoursesb = serialCourse == null ? null : JsonSerializer.Deserialize<Courses>(serialCourseb);

                string serialAssignment2 = HttpContext.Session.GetString("userAssignments");
                Assignments userAssignments3 = serialAssignment2 == null ? null : JsonSerializer.Deserialize<Assignments>(serialAssignment2);


                //reload timespans
                string serialTimes = HttpContext.Session.GetString("courseTimes");
                List<TimeStamp> times = JsonSerializer.Deserialize<List<TimeStamp>>(serialTimes);
                userCourses.RefactorTimeSpans(times);

                ViewData["UserCourses"] = userCourses;
                ViewData["Message"] = session;
                ViewData["userAssignments"] = userAssignments3;
                return View("~/Views/Home/Index.cshtml");
            }

            //get assignments, and selected assignment
            string serialAssignment = HttpContext.Session.GetString("userAssignments");
            Assignments userAssignments = serialAssignment == null ? null : JsonSerializer.Deserialize<Assignments>(serialAssignment);

            List<Assignment> selectedAssignments = new List<Assignment>();

            if (userAssignments.AssignmentList.Count(x => x.CourseID == id) == 1)
            {
                selectedAssignments = userAssignments.AssignmentList.Where(x => x.CourseID == id).ToList();
            }


            SpecificCourse dummy = new SpecificCourse()
            {
                AssignmentList = new List<Assignment>()
            };

            //perform Delete
            bool result = DeleteXAssignmentHelper(_context, userAssignments, dummy, selectedAssignments, Environment);

            List<Enrollment> courseEnrollments = _context.Enrollments.Where(x => x.courseID == id).ToList();
            foreach(Enrollment e in courseEnrollments)
            {
                _context.Enrollments.Remove(e);
            }
            Course selectedCourse = userCourses.CourseList.Where(x => x.CourseID == id).Single();
            _context.Courses.Remove(selectedCourse);
            _context.SaveChanges();
            userCourses.CourseList.Remove(selectedCourse);

            //update session saved courses
            HttpContext.Session.SetString("userCourses", JsonSerializer.Serialize(userCourses));
            HttpContext.Session.SetString("userAssignments", JsonSerializer.Serialize(userAssignments));
            return AddClass();
        }
        //(end)Deletions of a course Logics(end)-------------------------------

        //(begin)Deletions of an Assignment Logics(begin)-----------------------
        [HttpGet]
        public IActionResult DeleteAssignment(int idAssignment)
        {
            //get assignments, and selected assignment
            string serialAssignment = HttpContext.Session.GetString("userAssignments");
            Assignments userAssignments = serialAssignment == null ? null : JsonSerializer.Deserialize<Assignments>(serialAssignment);
            Assignment selectedAssignment = new Assignment();
            if (userAssignments.AssignmentList.Count(x => x.AssignmentID == idAssignment) == 1)
            {
                selectedAssignment = userAssignments.AssignmentList.Where(x => x.AssignmentID == idAssignment).Single();
            }
            else
            {
                string serialUser = HttpContext.Session.GetString("userInfo");
                UserSession session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);

                string serialCourse = HttpContext.Session.GetString("userCourses");
                Courses userCourses = serialCourse == null ? null : JsonSerializer.Deserialize<Courses>(serialCourse);

                string serialAssignment2 = HttpContext.Session.GetString("userAssignments");
                Assignments userAssignments3 = serialAssignment2 == null ? null : JsonSerializer.Deserialize<Assignments>(serialAssignment2);


                //reload timespans
                string serialTimes = HttpContext.Session.GetString("courseTimes");
                List<TimeStamp> times = JsonSerializer.Deserialize<List<TimeStamp>>(serialTimes);
                userCourses.RefactorTimeSpans(times);

                ViewData["UserCourses"] = userCourses;
                ViewData["Message"] = session;
                ViewData["userAssignments"] = userAssignments3;
                ViewData["url"] = "/Home/Index";
                return View("~/Views/Home/Index.cshtml");
            }
             
            //get course
            string courseKey = "course" + selectedAssignment.CourseID;
            string serialSelected = HttpContext.Session.GetString(courseKey);
            SpecificCourse course = JsonSerializer.Deserialize<SpecificCourse>(serialSelected);

            List<Assignment> selectedAssignments = new List<Assignment>();
            selectedAssignments.Add(selectedAssignment);

            //perform Delete
            bool result = DeleteXAssignmentHelper(_context, userAssignments, course, selectedAssignments, Environment);

            //update session saved courses
            HttpContext.Session.SetString("userAssignments", JsonSerializer.Serialize(userAssignments));
            HttpContext.Session.SetString(courseKey, JsonSerializer.Serialize(course));
            
            

            return CourseEdit(selectedAssignment.CourseID);
        }

        //Helper functions for Deletion(s)//
        public static bool DeleteXAssignmentHelper(cs3750Context _context, Assignments userAssignments, SpecificCourse course, List<Assignment> selectedAssignments, IHostingEnvironment Environment)
        {
            try
            {
                foreach (Assignment selectedAssignment in selectedAssignments)
                {
                    //remove assignment from lists and db
                    _context.Assignments.Remove(selectedAssignment);
                    userAssignments.AssignmentList.Remove(userAssignments.AssignmentList.Where(x=>x.AssignmentID==selectedAssignment.AssignmentID).Single());
                    course.AssignmentList.Remove(course.AssignmentList.Where(x=>x.AssignmentID==selectedAssignment.AssignmentID).Single());

                    //remove submissions
                    List<Submission> submissionsForDelete = _context.Submissions.Where(x => x.AssignmentID == selectedAssignment.AssignmentID).ToList();
                    foreach (Submission s in submissionsForDelete)
                    {
                        _context.Submissions.Remove(s);
                    }
                    
                    string path = Path.Combine(Environment.WebRootPath,"Submissions/" + selectedAssignment.AssignmentID);
                    if (Directory.Exists(path))
                    {
                        Directory.Delete(path, true);
                    }
                    //end remove submissions
                }
                //save database ane return affirmation
                _context.SaveChanges();
                return true;
            }
            catch(Exception e)
            {
                return false;
            }
        }


        //(end)Deletions of an Assignment Logic (end) ----------------------

        //-------------------------------Specific Course Edit logic Begin--------------
        [HttpGet]
        public IActionResult CourseEdit(int id)
        {
            string courseKey = "course" + id;
            string serialUser = HttpContext.Session.GetString("userInfo");
            UserSession session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);



            string serialSelected = HttpContext.Session.GetString(courseKey);
            SpecificCourse course = new SpecificCourse();

cs3750LMS/cs3750LMS/Views/Instructor/SubmissionDetail.cshtml
@model cs3750LMS.Models.validation.GradeValidation;
@{
    UserSession user = (UserSession)ViewData["Message"];
    cs3750LMS.Models.general.SIUser student = (cs3750LMS.Models.general.SIUser)ViewData["Student"];
    cs3750LMS.Models.general.SpecificAssignment assignment = (cs3750LMS.Models.general.SpecificAssignment)ViewData["Assignment"];
    Submission submission = (Submission)ViewData["Submission"];
    string file = (string)ViewData["File"];
    ViewData["Title"] = "Courses";
}
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

<div id="SubmissionDetailView" class="container">
    <h1 class="text-center">@assignment.Selection.Title</h1>
    <form asp-action="SubmissionDetail" method="post" class="w-75 mx-auto mt-5">
        <div asp-validation-summary="ModelOnly"></div>
        <h2>
            Student Name: <span>@student.FirstName</span>
            <span>@student.LastName</span>
        </h2>
        <div>
            <input type="text" asp-for="SubmissionID" name="SubmissionID" class="form-control" hidden value="@submission.SubmissionID" />
        </div>
        <div>
            <input type="text" asp-for="AssignmentID" name="AssignmentID" class="form-control" hidden value="@submission.AssignmentID" />
        </div>
        <div>
            <input type="text" asp-for="StudentID" name="StudentID" class="form-control" hidden value="@submission.StudentID" />
        </div>

        <div class="form-group row">
            <div class="col-sm-12 col-lg-2 d-flex align-items-center justify-content-sm-center justify-content-lg-end mb-sm-3 mb-lg-0 p-0">
                <label asp-for="SubmissionDate" class="control-label mb-0 text-sm-center text-lg-end">Submission Date:</label>
            </div>
            <div class="col-sm-12 col-lg-10">
                <input id="SubmissionDate" type="text" asp-for="SubmissionDate" name="SubmissionDate" class="form-control" value="@submission.SubmissionDate" disabled />
            </div>
        </div>
        <div>
            <input type="text" asp-for="SubmissionType" name="SubmissionType" class="form-control" hidden value="@submission.SubmissionType" />
        </div>

        <div class="form-group row">
            <div class="col-sm-12 col-lg-2 d-flex align-items-center justify-content-sm-center justify-content-lg-end mb-sm-3 mb-lg-0 p-0">
                <label asp-for="Contents" class="control-label mb-0 text-sm-center text-lg-end">Submission</label>
            </div>
            <div class="col-sm-12 col-lg-10">
                @if (@submission.SubmissionType != 0)
                {
                    <textarea class="form-control" type="text" maxlength="1000" rows="3" name="Contents" readonly>@submission.Contents</textarea>
                }
                else
                {
                    <span>@submission.Contents</span>
                    <a href=@file class="btn btn-success" download><i class="bi bi-download"></i> File Download</a>            
                }
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-12 col-lg-2 d-flex align-items-center justify-content-sm-center justify-content-lg-end mb-sm-3 mb-lg-0 p-0">
                <label asp-for="Grade" class="control-label mb-0 text-sm-center text-lg-end">Grade</label>
            </div>
            <div class="col-sm-3">
                <input id="Grade" type="text" asp-for="Grade" name="Grade" class="form-control AddField" required placeholder=@submission.Grade />
            </div>
            <div class="col-sm-3">
                / @assignment.Selection.MaxPoints
            </div>
            <div class="col-sm-12 col-lg-10">
                <span class="text-danger" asp-validation-for="Grade"></span>
            </div>
        </div>

        <div class="form-group text-center">
            <input type="submit" value="Update Grade" class="btn btn-primary mx-2" />
            <a type="button" asp-controller="Instructor" asp-action="Submissions" asp-route-id="@assignment.Selection.AssignmentID" class="btn btn-warning">Cancel</a>
        </div>

    </form>
</div>

cs3750LMS/cs3750LMS/Views/Instructor/Submissions.cshtml
@{
    UserSession user = (UserSession)ViewData["Message"];
    cs3750LMS.Models.general.SIUsers students = (cs3750LMS.Models.general.SIUsers)ViewData["Students"];
    cs3750LMS.Models.general.SpecificAssignment assignment = (cs3750LMS.Models.general.SpecificAssignment)ViewData["ClickedAssignment"];
    ViewData["Title"] = "Courses";
    ViewBag.assignment = Newtonsoft.Json.JsonConvert.SerializeObject(assignment);
    ViewBag.students = Newtonsoft.Json.JsonConvert.SerializeObject(students);
}
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script type="text/javascript">
        var _assignment = @Html.Raw(ViewBag.assignment);
        var _students = @Html.Raw(ViewBag.students);
        var graphData = [['Student Name', 'Grade']];
        // Populate graphData
        for (var i = 0; i < _assignment.SubmissionList.length; i++) {
            // Check if assignment has been graded
            if (_assignment.SubmissionList[i].Grade != -1) {
                var studentGrade = _assignment.SubmissionList[i].Grade;
                var studentName;

                // Find Student Name
                for (var j = 0; j < _students.SIUserList.length; j++) {
                    if (_students.SIUserList[j].UserId == _assignment.SubmissionList[i].StudentID) {
                        studentName = _students.SIUserList[j].FirstName + " " + _students.SIUserList[j].LastName;
                        break;
                    }
                }

                // Package
                var packagedStudent = [studentName, studentGrade];
                // Add to graph data
                graphData.push(packagedStudent);
            }
        }
        // Create graph
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable(graphData);

            var options = {
                title: 'Grade distributions',
                legend: { position: 'none' },
                backgroundColor: { fill: 'transparent' }
            };

            var chart = new google.visualization.Histogram(document.getElementById('chart_div'));
            chart.draw(data, options);
        }
    </script>
}

<div id="SubmissionView" class="container">
    <h1 class="text-center">@assignment.Selection.Title</h1>
    <h2 class="text-center mt-3">Submissions</h2>
    <div id="chart_div" style="width: 400px; height: 400px;" class="mx-auto"></div>
    <table class="table table-hover bg-white mt-2">
        <thead>
            <tr>
                <th scope="col">Student Name</th>
                <th scope="col">Submission Date</th>
                <th scope="col">Grade</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < assignment.SubmissionList.Count; i++)
            {
                <tr>
                    <th scope="row">
                        <span>@students.SIUserList.Find(x => x.UserId == assignment.SubmissionList[i].StudentID).FirstName</span>
                        <span>@students.SIUserList.Find(x => x.UserId == assignment.SubmissionList[i].StudentID).LastName</span>
                    </th>
                    <td scope="row">@assignment.SubmissionList[i].SubmissionDate</td>
                    <td scope="row">
                        @if (assignment.SubmissionList[i].Grade != -1)
                        {
                            <span>@assignment.SubmissionList[i].Grade</span> }
                        else
                        {
                            <span>-</span>}
                    </td>
                    <td>
                        <a type="button" asp-controller="Instructor" asp-action="SubmissionDetail" asp-route-id="@assignment.SubmissionList[i].SubmissionID" class="btn btn-success">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
</div>