cs3750LMS/cs3750LMS/Controllers/PublicController.cs
using cs3750LMS.DataAccess;
using cs3750LMS.Models;
using cs3750LMS.Models.entites;
using cs3750LMS.Models.general;
using cs3750LMS.Models.validation;
using cs3750LMS.Models.Repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace cs3750LMS.Controllers
{
    public class PublicController : Controller
    {
        private readonly cs3750Context _context;
        private IHostingEnvironment Environment;
        private readonly INotificationRepository _notification;
        public PublicController(cs3750Context context, IHostingEnvironment _enrionment, INotificationRepository notification)
        {
            _context = context;
            Environment = _enrionment;
            _notification = notification;
        }


        //sends user to calendar page if logged in and passes needed session data to view
        public IActionResult Calendar()
        {
            if (HttpContext.Session.Get<string>("user") != null)
            {
                string serialUser = HttpContext.Session.GetString("userInfo");
                UserSession session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);

                // Courses
                string serialCourse = HttpContext.Session.GetString("userCourses");
                Courses userCourses = serialCourse == null ? null : JsonSerializer.Deserialize<Courses>(serialCourse);

                // Assignments
                string serialAssignment = HttpContext.Session.GetString("userAssignments");
                Assignments userAssignments = serialAssignment == null ? null : JsonSerializer.Deserialize<Assignments>(serialAssignment);

                //reload timespans
                string serialTimes = HttpContext.Session.GetString("courseTimes");
                List<TimeStamp> times = JsonSerializer.Deserialize<List<TimeStamp>>(serialTimes);
                userCourses.RefactorTimeSpans(times);

                ViewData["UserCourses"] = userCourses;
                ViewData["UserAssignments"] = userAssignments;
                ViewData["Message"] = session;
                ViewData["url"] = "/Public/Calendar";
                return View();
            }
            return View("~/Views/Home/Login.cshtml");
        }

        //sends user to profile page if logged in and passes needed session data to view
        public IActionResult Profile()
        {
            if (HttpContext.Session.Get<string>("user") != null)
            {
                string serialStates = HttpContext.Session.GetString("States");
                States states = new States();
                if (serialStates != null)
                {
                    states = JsonSerializer.Deserialize<States>(serialStates);
                }
                else
                {
                    states.StatesList = _context.States.ToList();
                    HttpContext.Session.SetString("States", JsonSerializer.Serialize(states));
                }

                string serialUser = HttpContext.Session.GetString("userInfo");
                UserSession session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);

                ViewData["States"] = states;
                ViewData["Message"] = session;
                ViewData["url"] = "/Public/Profile";
                return View();
            }
            return View("~/Views/Home/Login.cshtml");
        }


        //updates user profile to database from the profile page
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProfile([Bind("ProfileImage,Email,FirstName,LastName,Birthday,ProfileImage,Address1,Address2,City,State,Zip,Phone,GitHubLink,TwitterLink,LinkedInLink,Bio")] UserValidationUpdate testUser)
        {
            User users = new User();
            bool updateSuccess = false;
            if (ModelState.IsValid)
            {
                if (_context.Users.Count(e => e.Email == testUser.Email) == 1)
                {
                    updateSuccess = ProfileDBUpdate(testUser, _context);
                }
            }
            UserSession session;
            if (updateSuccess)
            {
                users = _context.Users.Where(e => e.Email == testUser.Email).Single();
                session = new UserSession
                {
                    UserId = users.UserId,
                    Email = users.Email,
                    FirstName = users.FirstName,
                    LastName = users.LastName,
                    Birthday = users.Birthday,
                    AccountType = users.AccountType,
                    ProfileImage = users.ProfileImage,
                    Address1 = users.Address1,
                    Address2 = users.Address2,
                    City = users.City,
                    State = users.State,
                    Zip = users.Zip,
                    Phone = users.Phone,
                    LinkedIn = users.LinkedIn,
                    Github = users.Github,
                    Twitter = users.Twitter,
                    Bio = users.Bio
                };
                HttpContext.Session.SetString("userInfo", JsonSerializer.Serialize(session));
            }
            else
            {
                string serialUser = HttpContext.Session.GetString("userInfo");
                session = serialUser == null ? null : JsonSerializer.Deserialize<UserSession>(serialUser);
            }

            session.IsUpdate = updateSuccess;

            string serialStates = HttpContext.Session.GetString("States");
            States states = new States();
            if (serialStates != null)
            {
                states = JsonSerializer.Deserialize<States>(serialStates);
            }
            else
            {
                states.StatesList = _context.States.ToList();
                HttpContext.Session.SetString("States", JsonSerializer.Serialize(states));
            }



            ViewData["States"] = states;
            ViewData["Message"] = session;
            ViewData["url"] = "/Public/Profile";
            return View("Profile");
        }

        public static String Sha256(String value)
        {
            StringBuilder hash = new StringBuilder();

            SHA256 security = SHA256.Create();
            Encoding enc = Encoding.UTF8;
            Byte[] result = security.ComputeHash(enc.GetBytes(value));

            foreach (byte b in result)
                hash.Append(b.ToString());

            return hash.ToString();
        }

        public bool ProfileDBUpdate(UserValidationUpdate updateUser, cs3750Context _context)
        {
            try
            {
                User users = new User();

                users = _context.Users.Where(x => x.Email == updateUser.Email).Single();
                users.Email = updateUser.Email;
                users.FirstName = updateUser.FirstName;
                users.LastName = updateUser.LastName;
                users.Phone = updateUser.Phone;
                users.Birthday = updateUser.Birthday;

                if (updateUser.ProfileImage != null)
                {
                    //start picture logic
                    string wwwPath = this.Environment.WebRootPath;
                    string contentPath = this.Environment.ContentRootPath;
                    string path = Path.Combine(this.Environment.WebRootPath, "Images");

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    string dbPath = Path.GetFileName(updateUser.ProfileImage.FileName);                   //name of file, could save to db as well
                    string FullPath = Path.Combine(path, dbPath);                               //save to database for later reference

                    //delete from files
                    if (System.IO.File.Exists(users.ProfileImage))
                    {
                        System.IO.File.Delete(users.ProfileImage);
                    }
                    //add to files
                    using (FileStream stream = new FileStream(FullPath, FileMode.Create))
                    {
                        updateUser.ProfileImage.CopyTo(stream);
                    }
                    users.ProfileImage = "/Images/" + updateUser.ProfileImage.FileName;
                }

                //////////////////////////end pic logic
                users.Address1 = updateUser.Address1;
                users.Address2 = updateUser.Address2;
                users.City = updateUser.City;
                users.State = updateUser.State;
                users.Zip = updateUser.Zip;
                users.Phone = updateUser.Phone;
                users.LinkedIn = updateUser.LinkedInLink;
                users.Github = updateUser.GitHubLink;
                users.Twitter = updateUser.TwitterLink;
                users.Bio = updateUser.Bio;

                _context.SaveChanges();
                return true;
            } 
            catch
            {
                return false;
            }
            
        }



        public bool CreateNotification(int recipientId, int referenceId, string type, string message, INotificationRepository _noti)
        {
            //create notification for graded assignment. 
            Notification noti = new Notification
            {

cs3750LMS/cs3750LMS/Views/Shared/_Layout.cshtml
@{
    UserSession show = (UserSession)ViewData["Message"];
    IEnumerable<Notification> notifications = null;
    if (show != null)
    {
        notifications = _notification.GetAllUserNotifications(show.UserId);
    }
    string url = (string)ViewData["url"];
}   

@inject cs3750LMS.Models.Repository.INotificationRepository _notification

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cs3750LMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/96bd72d7d0.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> @*Google Graphs*@   

</head>
<body class="d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BinaryEntanglersLMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-door"></i> Home</a>
                        </li>
                        @if (show == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login"><i class="bi bi-key"></i> Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SignUp"><i class="bi bi-person-plus"></i> Sign Up</a>
                            </li>
                        }
                        @if (show != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Public" asp-action="Profile"><i class="bi bi-person"></i> Profile</a>
                            </li>
                        }
                        @if (show != null && show.AccountType == 1) //Instructor
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Instructor" asp-action="AddClass"><i class="bi bi-clipboard-plus"></i> Add Class</a>
                            </li>
                        }
                        @if (show != null && show.AccountType == 0)  //Student
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Register"><i class="bi bi-clipboard-plus"></i> Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Payment"><i class="bi bi-credit-card"></i> Payment</a>
                            </li>
                        }
                        @if (show != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Public" asp-action="Calendar"><i class="bi bi-calendar-week"></i> Calendar</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="LogOut"><i class="bi bi-door-open"></i> Log Out</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link" id="notiDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i id="bellIcon" class="far fa-bell fa-lg"></i></a>
                                @if (notifications.Count() > 0)
                                {
                                <div class="dropdown-menu" id="notiMenu">
                                    @for (int i = 0; i < notifications.Count(); i++)
                                    {

                                        //Each Account Type and Notification Type combination will have a different <a></a> link when clicked.
                                        if (show.AccountType == 0 && notifications.ElementAt(i).NotificationType == "Assignment")  //student
                                        {
                                            <div class="dropdown-item">
                                                <div class="row">
                                                    <div class="col-12 d-flex flex-row align-items-end justify-content-end">
                                                        <form asp-controller="Home" asp-action="DeleteNotification" method="post">
                                                            <div style="display:none">
                                                                <input type="number" name="id" value=@notifications.ElementAt(i).NotificationID />
                                                                <input type="text" name="pageURL" value=@url />
                                                            </div>
                                                            <button type="submit" class="btn btn-danger m-0 py-0 px-1"><i id="notificationXicon" class="far fa-window-close fa-med icorrect noti m-0 p-0"></i></button>
                                                        </form>
                                                    </div>
                                                    <div class="col-12">
                                                        <a asp-controller="Student" asp-action="ViewCourse" asp-route-id=@notifications.ElementAt(i).ReferenceID>
                                                            @notifications.ElementAt(i).Message
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            if (notifications.Count() > 1 && notifications.Count() != i + 1)
                                            {
                                                <hr />
                                            }
                                        }
                                        else if (show.AccountType == 1 && notifications.ElementAt(i).NotificationType == "Assignment") //teacher
                                        {
                                            <div class="dropdown-item">
                                                <div class="row">
                                                    <div class="col-12 d-flex flex-row align-items-end justify-content-end">
                                                        <form asp-controller="Home" asp-action="DeleteNotification" method="post">
                                                            <div style="display:none">
                                                                <input type="number" name="id" value=@notifications.ElementAt(i).NotificationID />
                                                                <input type="text" name="pageURL" value=@url/>
                                                            </div>
                                                            <button type="submit" class="btn btn-danger m-0 py-0 px-1"><i id="notificationXicon" class="far fa-window-close fa-med icorrect noti m-0 p-0"></i></button>
                                                        </form>
                                                    </div>
                                                    <div class="col-12">
                                                        <a asp-controller="Instructor" asp-action="CourseEdit" asp-route-id=@notifications.ElementAt(i).ReferenceID>
                                                            @notifications.ElementAt(i).Message
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            if (notifications.Count() > 1 && notifications.Count() != i + 1)
                                            {
                                                <hr />
                                            }
                                        }
                                    }
                                </div>
                                    <input id="PassingNotificationCountToJavaScript" hidden value=@notifications.Count()>
                                }
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid flex-grow-1 d-flex flex-column pt-3">
        <main role="main" class="pb-3 flex-grow-1 d-flex flex-column">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - cs3750LMS
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>